line_wrapping: true

keymap:
  normal:
    t: "cursor::move_down"
    s: "cursor::move_up"
    r: "cursor::move_right"
    c: "cursor::move_left"
    a:
      - "cursor::move_right"
      - "application::switch_to_insert_mode"
    G: "cursor::move_to_last_line"
    g: "cursor::move_to_first_line"
    k: "application::switch_to_line_jump_mode"
    d:
      - "cursor::move_to_start_of_previous_token"
      - "buffer::delete_token"
    w: "buffer::save"
    ctrl-r: "buffer::redo"
    $: "cursor::move_to_end_of_line"
    "^": "cursor::move_to_start_of_line"
    ":": "application::switch_to_command_mode"
